### ISSUE TITLE
Syntax error on Python 2.7.11

### ISSUE THREAD

**Issue by PherricOxide** [bradysalz/mint-sankey#2]
$ python --version
Python 2.7.11

$ python sankey_gen.py .
  File "sankey_gen.py", line 16
    def parse_csv(fname: str) -> List[Transaction]:
                       ^
SyntaxError: invalid syntax

**Comment by bradysalz** [comment]
Hey there, I'm guessing that's due to the `typing` style arguments. Like the pre-reqs say in the `README`, this requires Python3.6 or higher.
